name = "LandSea"
uuid = "cbf7bb22-a1a6-46cb-8b24-174e3bc5fc04"
authors = ["Nathanael Wong <natgeo.wong@outlook.com>"]
version = "0.0.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
julia = "^1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
